name: Build SunamoYaml

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoYaml
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoYaml/SunamoYaml.csproj

    - name: Build
      run: dotnet build SunamoYaml/SunamoYaml.csproj --configuration Release --no-restore

  test:
    name: Test SunamoYaml.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoYaml.Tests/SunamoYaml.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoYaml.Tests/SunamoYaml.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoYaml.Tests/SunamoYaml.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
